# Usa una imagen de Maven para compilar
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Usa una imagen más ligera para correr la app
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Render expone el puerto dinámicamente
ENV PORT=8080
EXPOSE 8080

CMD ["java", "-jar", "app.jar"]